[versions]
kotlin = "2.2.21"
coroutines = "1.10.2"
agp = "8.13.0"

core = "1.17.0"
appCompat = "1.7.1"
lifecycle = "2.10.0"
viewModelCompose = "2.10.0"
mockk = "1.14.6"
hilt = "2.57.2"
hiltAndroidx = "1.3.0"
testRunner = "1.6.1"
testJetpack = "2.2.0"
composeMaterial3 = "1.4.0"
accompanist = "0.37.3"
workManager = "2.11.0"
room = "2.8.4"
paparazzi = "2.0.0-alpha02"
composeDestinations = "2.3.0"
junit5 = "5.13.4"
firebaseCrashlyticsPlugin = "3.0.3"

ksp = "2.3.0"
jacoco = "0.8.12"
androidxComposeBom = "2025.12.00"
chrisBanesComposeBom = "2023.04.00-beta02"
reordeable = "3.0.0"
collectionsImmutable = "0.4.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
benchmarkBaselineProfileGradlePlugin = "1.4.1"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
profileinstaller = "1.4.1"
playReview = "2.0.2"
kotlinxSerialization = "1.9.0"
material = "1.13.0"

[libraries]
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltAndroidx" }
hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.3.0"
hilt-work = "androidx.hilt:hilt-work:1.3.0"
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
startup = "androidx.startup:startup-runtime:1.2.0"
preferences = "androidx.preference:preference-ktx:1.2.1"
preferences-datastore = "androidx.datastore:datastore-preferences:1.1.7"
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
compose-bom-alpha = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "chrisBanesComposeBom" }
compose-activity = "androidx.activity:activity-compose:1.9.3"
compose-ui = { module = "androidx.compose.ui:ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-adaptative-navigation = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
compose-material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class" }
compose-ui-text-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
work = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
work-testing = { module = "androidx.work:work-testing", version.ref = "workManager" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
calendar = "com.kizitonwose.calendar:compose:2.9.0"
android-junit = "androidx.test.ext:junit-ktx:1.3.0"
firebase-bom = "com.google.firebase:firebase-bom:33.5.1"
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-config = { module = "com.google.firebase:firebase-config" }
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinations" }
compose-destinations-bottomsheet = { module = "io.github.raamcosta.compose-destinations:bottom-sheet", version.ref = "composeDestinations" }
reordeable = { group = "sh.calvin.reorderable", name = "reorderable", version.ref = "reordeable" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

play-review = {  group = "com.google.android.play", name = "review-ktx", version.ref = "playReview" }

junit = "junit:junit:4.13.2"
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
truth = "androidx.test.ext:truth:1.7.0"
androidx-test = { module = "androidx.arch.core:core-testing", version.ref = "testJetpack" }
turbine = "app.cash.turbine:turbine:1.2.1"
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "testRunner" }
android-desugarjdk = "com.android.tools:desugar_jdk_libs:2.1.3"
robolectric = "org.robolectric:robolectric:4.12"
testparameterinjector = "com.google.testparameterinjector:test-parameter-injector:1.13"
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "collectionsImmutable" }

androidGradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detektGradle = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.23.6"
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-benchmark-baseline-profile-gradle-plugin = { group = "androidx.benchmark", name = "benchmark-baseline-profile-gradle-plugin", version.ref = "benchmarkBaselineProfileGradlePlugin" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

# Plugins
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
